name: Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          user: xjuunn
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Shanghai

      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}

          base: ""
          config_timezone: Asia/Shanghai

          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_indepth: no
          plugin_languages_analysis_timeout: 15